packages:
    - 'packages/*'

catalog:
    '@0zd0/nx-oxfmt': '^0.1.0'
    '@nx/js': '22.1.3'
    '@nx/vite': '22.1.3'
    '@nx/vitest': '22.1.3'
    '@oclif/core': '^4.8.0'
    '@oclif/test': '^4.1.15'
    '@rollup/pluginutils': '^5.3.0'
    '@types/estree': '^1.0.8'
    '@types/node': '^24.10.1'
    '@types/react': '^19.2.7'
    '@types/react-dom': '^19.2.3'
    '@typescript/native-preview': '7.0.0-dev.20260204.1'
    '@vitejs/plugin-react-swc': '^4.2.3'
    '@vitest/coverage-v8': '^4.0.0'
    '@vitest/ui': '^4.0.0'
    '@wordpress/i18n': '^6.9.0'
    'estree-walker': '^3.0.3'
    'fast-glob': '^3.3.3'
    'is-reference': '^3.0.3'
    'jiti': '^2.6.1'
    'magic-string': '^0.30.21'
    'nx': '22.1.3'
    'oclif': '^4.22.52'
    'oxfmt': '^0.28.0'
    'radash': '^12.1.1'
    'rollup': '^4.53.3'
    'swc-loader': '0.1.15'
    'syncpack': '^14.0.0-alpha.29'
    'ts-morph': '^27.0.2'
    'ts-node': '^10.9.2'
    'tsdown': '^0.16.8'
    'typescript': '^5.9.3'
    'vite': '^7.2.4'
    'vite-tsconfig-paths': '^5.1.4'
    'vitest': '^4.0.14'
    'zod': '^4.1.13'
    'oxc-resolver': '^11.17.1'

catalogs:
    peers:
        vite: ^7.0.0
        rollup: ^4.0.0